{% set name = "valida" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/valida-{{ version }}.tar.gz
  sha256: a98d57eab802dab82f9da90ae67f9ffef30cb4806d730da8e2c86aaeb5212c73

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<3.12
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.8,<3.12
    - ruamel.yaml >=0.17.20,<0.18.0

test:
  imports:
    - valida
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hpcflow/valida
  summary: Comprehensive validation library for nested data structures.
  description: |
    Valida is a comprehensive validation library for nested data structures.
    It was developed using funding from the LightForm EPSRC programme grant (EP/R001715/1).
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - aplowman
